server:
  port: 8080

spring:
  datasource:
    username: xxx
    password: xxx
    url: jdbc:mysql://xxx:3306/xxx?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active:
      - cookie

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
  mapper-locations:
    - classpath:mapper/*Mapper.xml



